// AI Assistant telemetry events generated by the pre-PR-#40 EventHorizon CLI
// (the last revision using the Trackable + concrete `*Event` pattern). Vendored
// here because the published EventHorizonSDK binary does not yet ship AI Assistant
// types, while the post-PR-#40 generator emits a factory `Event` pattern that
// hides per-property visibility behind a closed `Event.Property` API.
//
// Regenerate by:
//   1. cd ~/Projects/EventHorizon && git checkout 7eab0241be1d
//   2. ./gradlew :event-horizon-cli:installDist
//   3. event-horizon-cli --input-file <stripped-schema.yml> \
//        --output-path . --output-format swift --output-platform ios
//   4. Delete the `EventHorizon` class and `Trackable` protocol declarations
//      from the output (already provided by EventHorizonSDK).
//
// Replace with generated types from a bumped EventHorizonSDK once
// https://github.com/Automattic/EventHorizon/pull/<TBD> fixes Event property
// visibility and the iOS SDK is republished.

import EventHorizonSDK
import Foundation

/**
 * The first accepted user request starts a new assistant conversation. */
public struct AiAssistantConversationStartedEvent: Trackable {

  public static let eventName: String = "ai_assistant_conversation_started"
  /**
   * Opaque identifier for the user-visible assistant conversation. */
  public let conversationId: String
  /**
   * Opaque client-generated identifier for the accepted assistant request. */
  public let requestId: String
  /**
   * Opaque identifier for the assistant response message associated with the request. */
  public let messageId: String
  public var analyticsName: String {
    return AiAssistantConversationStartedEvent.eventName
  }
  public let analyticsProperties: [String: CustomStringConvertible]
  public var description: String {
    var parts: [String] = []
    parts.append("conversationId: \(conversationId)")
    parts.append("requestId: \(requestId)")
    parts.append("messageId: \(messageId)")
    return "AiAssistantConversationStartedEvent(\(parts.joined(separator: ", ")))"
  }

  public init(
    conversationId: String,
    requestId: String,
    messageId: String
  ) {
    self.conversationId = conversationId
    self.requestId = requestId
    self.messageId = messageId
    var _props: [String: CustomStringConvertible] = [:]
    _props["conversation_id"] = conversationId
    _props["request_id"] = requestId
    _props["message_id"] = messageId
    self.analyticsProperties = _props
  }

  public static func ==(lhs: AiAssistantConversationStartedEvent, rhs: AiAssistantConversationStartedEvent) -> Bool {
    return
      lhs.conversationId == rhs.conversationId &&
      lhs.requestId == rhs.requestId &&
      lhs.messageId == rhs.messageId
  }

  public func hash(into hasher: inout Hasher) {
    hasher.combine(conversationId)
    hasher.combine(requestId)
    hasher.combine(messageId)
  }

}

/**
 * A non-empty user request is accepted locally and assistant processing begins. */
public struct AiAssistantTurnStartedEvent: Trackable {

  public static let eventName: String = "ai_assistant_turn_started"
  public let conversationId: String
  public let requestId: String
  public let messageId: String
  public let isRetry: Bool
  public let completionStack: String?
  public let promptVersion: String?
  public let toolCatalogVersion: String?
  public var analyticsName: String {
    return AiAssistantTurnStartedEvent.eventName
  }
  public let analyticsProperties: [String: CustomStringConvertible]
  public var description: String {
    var parts: [String] = []
    parts.append("conversationId: \(conversationId)")
    parts.append("requestId: \(requestId)")
    parts.append("messageId: \(messageId)")
    parts.append("isRetry: \(isRetry)")
    parts.append("completionStack: \(String(describing: completionStack))")
    parts.append("promptVersion: \(String(describing: promptVersion))")
    parts.append("toolCatalogVersion: \(String(describing: toolCatalogVersion))")
    return "AiAssistantTurnStartedEvent(\(parts.joined(separator: ", ")))"
  }

  public init(
    conversationId: String,
    requestId: String,
    messageId: String,
    isRetry: Bool,
    completionStack: String? = nil,
    promptVersion: String? = nil,
    toolCatalogVersion: String? = nil
  ) {
    self.conversationId = conversationId
    self.requestId = requestId
    self.messageId = messageId
    self.isRetry = isRetry
    self.completionStack = completionStack
    self.promptVersion = promptVersion
    self.toolCatalogVersion = toolCatalogVersion
    var _props: [String: CustomStringConvertible] = [:]
    _props["conversation_id"] = conversationId
    _props["request_id"] = requestId
    _props["message_id"] = messageId
    _props["is_retry"] = isRetry
    if let completionStack {
      _props["completion_stack"] = completionStack
    }
    if let promptVersion {
      _props["prompt_version"] = promptVersion
    }
    if let toolCatalogVersion {
      _props["tool_catalog_version"] = toolCatalogVersion
    }
    self.analyticsProperties = _props
  }

  public static func ==(lhs: AiAssistantTurnStartedEvent, rhs: AiAssistantTurnStartedEvent) -> Bool {
    return
      lhs.conversationId == rhs.conversationId &&
      lhs.requestId == rhs.requestId &&
      lhs.messageId == rhs.messageId &&
      lhs.isRetry == rhs.isRetry &&
      lhs.completionStack == rhs.completionStack &&
      lhs.promptVersion == rhs.promptVersion &&
      lhs.toolCatalogVersion == rhs.toolCatalogVersion
  }

  public func hash(into hasher: inout Hasher) {
    hasher.combine(conversationId)
    hasher.combine(requestId)
    hasher.combine(messageId)
    hasher.combine(isRetry)
    hasher.combine(completionStack)
    hasher.combine(promptVersion)
    hasher.combine(toolCatalogVersion)
  }

}

/**
 * A model-requested tool call reaches a final runtime decision. */
public struct AiAssistantToolCallCompletedEvent: Trackable {

  public static let eventName: String = "ai_assistant_tool_call_completed"
  public let conversationId: String
  public let requestId: String
  public let messageId: String
  public let toolName: String
  public let status: AiAssistantToolStatusValue
  public let errorKind: AiAssistantErrorKindValue?
  public let durationMs: Int?
  public var analyticsName: String {
    return AiAssistantToolCallCompletedEvent.eventName
  }
  public let analyticsProperties: [String: CustomStringConvertible]
  public var description: String {
    var parts: [String] = []
    parts.append("conversationId: \(conversationId)")
    parts.append("requestId: \(requestId)")
    parts.append("messageId: \(messageId)")
    parts.append("toolName: \(toolName)")
    parts.append("status: \(status)")
    parts.append("errorKind: \(String(describing: errorKind))")
    parts.append("durationMs: \(String(describing: durationMs))")
    return "AiAssistantToolCallCompletedEvent(\(parts.joined(separator: ", ")))"
  }

  public init(
    conversationId: String,
    requestId: String,
    messageId: String,
    toolName: String,
    status: AiAssistantToolStatusValue,
    errorKind: AiAssistantErrorKindValue? = nil,
    durationMs: Int? = nil
  ) {
    self.conversationId = conversationId
    self.requestId = requestId
    self.messageId = messageId
    self.toolName = toolName
    self.status = status
    self.errorKind = errorKind
    self.durationMs = durationMs
    var _props: [String: CustomStringConvertible] = [:]
    _props["conversation_id"] = conversationId
    _props["request_id"] = requestId
    _props["message_id"] = messageId
    _props["tool_name"] = toolName
    _props["status"] = status.analyticsValue
    if let errorKind {
      _props["error_kind"] = errorKind.analyticsValue
    }
    if let durationMs {
      _props["duration_ms"] = durationMs
    }
    self.analyticsProperties = _props
  }

  public static func ==(lhs: AiAssistantToolCallCompletedEvent, rhs: AiAssistantToolCallCompletedEvent) -> Bool {
    return
      lhs.conversationId == rhs.conversationId &&
      lhs.requestId == rhs.requestId &&
      lhs.messageId == rhs.messageId &&
      lhs.toolName == rhs.toolName &&
      lhs.status == rhs.status &&
      lhs.errorKind == rhs.errorKind &&
      lhs.durationMs == rhs.durationMs
  }

  public func hash(into hasher: inout Hasher) {
    hasher.combine(conversationId)
    hasher.combine(requestId)
    hasher.combine(messageId)
    hasher.combine(toolName)
    hasher.combine(status)
    hasher.combine(errorKind)
    hasher.combine(durationMs)
  }

}

/**
 * A show_cards request is processed enough to know aggregate card quality counts. */
public struct AiAssistantShowCardsProcessedEvent: Trackable {

  public static let eventName: String = "ai_assistant_show_cards_processed"
  public let conversationId: String
  public let requestId: String
  public let messageId: String
  public let requestedCount: Int
  public let renderedCount: Int
  public let missingCount: Int
  public let rejectedCount: Int
  public var analyticsName: String {
    return AiAssistantShowCardsProcessedEvent.eventName
  }
  public let analyticsProperties: [String: CustomStringConvertible]
  public var description: String {
    var parts: [String] = []
    parts.append("conversationId: \(conversationId)")
    parts.append("requestId: \(requestId)")
    parts.append("messageId: \(messageId)")
    parts.append("requestedCount: \(requestedCount)")
    parts.append("renderedCount: \(renderedCount)")
    parts.append("missingCount: \(missingCount)")
    parts.append("rejectedCount: \(rejectedCount)")
    return "AiAssistantShowCardsProcessedEvent(\(parts.joined(separator: ", ")))"
  }

  public init(
    conversationId: String,
    requestId: String,
    messageId: String,
    requestedCount: Int,
    renderedCount: Int,
    missingCount: Int,
    rejectedCount: Int
  ) {
    self.conversationId = conversationId
    self.requestId = requestId
    self.messageId = messageId
    self.requestedCount = requestedCount
    self.renderedCount = renderedCount
    self.missingCount = missingCount
    self.rejectedCount = rejectedCount
    var _props: [String: CustomStringConvertible] = [:]
    _props["conversation_id"] = conversationId
    _props["request_id"] = requestId
    _props["message_id"] = messageId
    _props["requested_count"] = requestedCount
    _props["rendered_count"] = renderedCount
    _props["missing_count"] = missingCount
    _props["rejected_count"] = rejectedCount
    self.analyticsProperties = _props
  }

  public static func ==(lhs: AiAssistantShowCardsProcessedEvent, rhs: AiAssistantShowCardsProcessedEvent) -> Bool {
    return
      lhs.conversationId == rhs.conversationId &&
      lhs.requestId == rhs.requestId &&
      lhs.messageId == rhs.messageId &&
      lhs.requestedCount == rhs.requestedCount &&
      lhs.renderedCount == rhs.renderedCount &&
      lhs.missingCount == rhs.missingCount &&
      lhs.rejectedCount == rhs.rejectedCount
  }

  public func hash(into hasher: inout Hasher) {
    hasher.combine(conversationId)
    hasher.combine(requestId)
    hasher.combine(messageId)
    hasher.combine(requestedCount)
    hasher.combine(renderedCount)
    hasher.combine(missingCount)
    hasher.combine(rejectedCount)
  }

}

/**
 * The merchant taps an assistant-rendered card or card action. */
public struct AiAssistantCardTappedEvent: Trackable {

  public static let eventName: String = "ai_assistant_card_tapped"
  public let conversationId: String
  public let requestId: String
  public let messageId: String
  public let cardFamily: AiAssistantCardFamilyValue
  public let actionFamily: AiAssistantActionFamilyValue
  public var analyticsName: String {
    return AiAssistantCardTappedEvent.eventName
  }
  public let analyticsProperties: [String: CustomStringConvertible]
  public var description: String {
    var parts: [String] = []
    parts.append("conversationId: \(conversationId)")
    parts.append("requestId: \(requestId)")
    parts.append("messageId: \(messageId)")
    parts.append("cardFamily: \(cardFamily)")
    parts.append("actionFamily: \(actionFamily)")
    return "AiAssistantCardTappedEvent(\(parts.joined(separator: ", ")))"
  }

  public init(
    conversationId: String,
    requestId: String,
    messageId: String,
    cardFamily: AiAssistantCardFamilyValue,
    actionFamily: AiAssistantActionFamilyValue
  ) {
    self.conversationId = conversationId
    self.requestId = requestId
    self.messageId = messageId
    self.cardFamily = cardFamily
    self.actionFamily = actionFamily
    var _props: [String: CustomStringConvertible] = [:]
    _props["conversation_id"] = conversationId
    _props["request_id"] = requestId
    _props["message_id"] = messageId
    _props["card_family"] = cardFamily.analyticsValue
    _props["action_family"] = actionFamily.analyticsValue
    self.analyticsProperties = _props
  }

  public static func ==(lhs: AiAssistantCardTappedEvent, rhs: AiAssistantCardTappedEvent) -> Bool {
    return
      lhs.conversationId == rhs.conversationId &&
      lhs.requestId == rhs.requestId &&
      lhs.messageId == rhs.messageId &&
      lhs.cardFamily == rhs.cardFamily &&
      lhs.actionFamily == rhs.actionFamily
  }

  public func hash(into hasher: inout Hasher) {
    hasher.combine(conversationId)
    hasher.combine(requestId)
    hasher.combine(messageId)
    hasher.combine(cardFamily)
    hasher.combine(actionFamily)
  }

}

/**
 * The assistant response reaches a final user-visible state for a request. */
public struct AiAssistantTurnCompletedEvent: Trackable {

  public static let eventName: String = "ai_assistant_turn_completed"
  public let conversationId: String
  public let requestId: String
  public let messageId: String
  public let outcome: AiAssistantTurnOutcomeValue
  public let durationMs: Int
  public let errorKind: AiAssistantErrorKindValue?
  public let isRetry: Bool?
  public let completionStack: String?
  public let promptVersion: String?
  public let toolCatalogVersion: String?
  public var analyticsName: String {
    return AiAssistantTurnCompletedEvent.eventName
  }
  public let analyticsProperties: [String: CustomStringConvertible]
  public var description: String {
    var parts: [String] = []
    parts.append("conversationId: \(conversationId)")
    parts.append("requestId: \(requestId)")
    parts.append("messageId: \(messageId)")
    parts.append("outcome: \(outcome)")
    parts.append("durationMs: \(durationMs)")
    parts.append("errorKind: \(String(describing: errorKind))")
    parts.append("isRetry: \(String(describing: isRetry))")
    parts.append("completionStack: \(String(describing: completionStack))")
    parts.append("promptVersion: \(String(describing: promptVersion))")
    parts.append("toolCatalogVersion: \(String(describing: toolCatalogVersion))")
    return "AiAssistantTurnCompletedEvent(\(parts.joined(separator: ", ")))"
  }

  public init(
    conversationId: String,
    requestId: String,
    messageId: String,
    outcome: AiAssistantTurnOutcomeValue,
    durationMs: Int,
    errorKind: AiAssistantErrorKindValue? = nil,
    isRetry: Bool? = nil,
    completionStack: String? = nil,
    promptVersion: String? = nil,
    toolCatalogVersion: String? = nil
  ) {
    self.conversationId = conversationId
    self.requestId = requestId
    self.messageId = messageId
    self.outcome = outcome
    self.durationMs = durationMs
    self.errorKind = errorKind
    self.isRetry = isRetry
    self.completionStack = completionStack
    self.promptVersion = promptVersion
    self.toolCatalogVersion = toolCatalogVersion
    var _props: [String: CustomStringConvertible] = [:]
    _props["conversation_id"] = conversationId
    _props["request_id"] = requestId
    _props["message_id"] = messageId
    _props["outcome"] = outcome.analyticsValue
    _props["duration_ms"] = durationMs
    if let errorKind {
      _props["error_kind"] = errorKind.analyticsValue
    }
    if let isRetry {
      _props["is_retry"] = isRetry
    }
    if let completionStack {
      _props["completion_stack"] = completionStack
    }
    if let promptVersion {
      _props["prompt_version"] = promptVersion
    }
    if let toolCatalogVersion {
      _props["tool_catalog_version"] = toolCatalogVersion
    }
    self.analyticsProperties = _props
  }

  public static func ==(lhs: AiAssistantTurnCompletedEvent, rhs: AiAssistantTurnCompletedEvent) -> Bool {
    return
      lhs.conversationId == rhs.conversationId &&
      lhs.requestId == rhs.requestId &&
      lhs.messageId == rhs.messageId &&
      lhs.outcome == rhs.outcome &&
      lhs.durationMs == rhs.durationMs &&
      lhs.errorKind == rhs.errorKind &&
      lhs.isRetry == rhs.isRetry &&
      lhs.completionStack == rhs.completionStack &&
      lhs.promptVersion == rhs.promptVersion &&
      lhs.toolCatalogVersion == rhs.toolCatalogVersion
  }

  public func hash(into hasher: inout Hasher) {
    hasher.combine(conversationId)
    hasher.combine(requestId)
    hasher.combine(messageId)
    hasher.combine(outcome)
    hasher.combine(durationMs)
    hasher.combine(errorKind)
    hasher.combine(isRetry)
    hasher.combine(completionStack)
    hasher.combine(promptVersion)
    hasher.combine(toolCatalogVersion)
  }

}

public enum AiAssistantActionFamilyValue: String {

  case openProduct = "open_product"
  case openOrder = "open_order"
  case openProductVariation = "open_product_variation"
  case openCustomer = "open_customer"
  case openAnalytics = "open_analytics"
  case unknown = "unknown"

  public var analyticsValue: String {
    return rawValue
  }

}

public enum AiAssistantCardFamilyValue: String {

  case product = "product"
  case variation = "variation"
  case analyticsStats = "analytics_stats"
  case order = "order"
  case customer = "customer"
  case unknown = "unknown"

  public var analyticsValue: String {
    return rawValue
  }

}

public enum AiAssistantErrorKindValue: String {

  case rateLimited = "rate_limited"
  case auth = "auth"
  case validationError = "validation_error"
  case serverError = "server_error"
  case cancelled = "cancelled"
  case timeout = "timeout"
  case network = "network"
  case unknown = "unknown"

  public var analyticsValue: String {
    return rawValue
  }

}

public enum AiAssistantToolStatusValue: String {

  case success = "success"
  case failure = "failure"

  public var analyticsValue: String {
    return rawValue
  }

}

public enum AiAssistantTurnOutcomeValue: String {

  case maxIterations = "max_iterations"
  case cancelledByUser = "cancelled_by_user"
  case failed = "failed"
  case success = "success"

  public var analyticsValue: String {
    return rawValue
  }

}
