AllCops:
  Exclude:
    - DerivedData/**/*
    - Pods/**/*
    - vendor/**/*
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - fastlane/Fastfile

Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Exclude:
    - fastlane/Fastfile

Layout/LineLength:
  Exclude:
    - fastlane/Fastfile
    - Podfile

Naming/FileName:
  Exclude:
    - fastlane/Matchfile
