# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#v1.5.0
    - automattic/git-s3-cache#v1.1.0:
        bucket: "a8c-repo-mirrors"
        repo: "woocommerce/woocommerce-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-13.4.1

steps:
  - label: "🛠 Release Build To Test Widgets"
    command: ".buildkite/commands/release-build.sh $BETA_RELEASE"
    env: *common_env
    plugins: *common_plugins
