# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: mac

env:
  IMAGE_ID: $IMAGE_ID

# This is the default pipeline – it will build and test the app
steps:
  - group: ":rocket: Prototype Build"
    if: build.branch == "test-fad-from-trunk"
    steps:
      - input: Deploy Prototype Build
        prompt: Share a Prototype Build via Firebase App Distribution?
        key: prototype_triggered
      - label: Prototype Build
        depends_on: prototype_triggered
        command: .buildkite/commands/prototype-build.sh
        plugins: [$CI_TOOLKIT]
        notify:
          - github_commit_status:
              context: Prototype Build From Trunk
