# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.18.2
    - automattic/git-s3-cache#1.1.4:
        bucket: "a8c-repo-mirrors"
        # This is not necessarily the actual name of the repo or the GitHub organization
        # it belongs to. It is the key used in the bucket, which is set based on
        # the Buildkite pipeline slug
        repo: "automattic/woocommerce-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-14.3.1

steps:

  - label: "🛠 Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build.sh $BETA_RELEASE"
    priority: 1
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"
