# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: mac

env:
  IMAGE_ID: $IMAGE_ID
  S3_BUCKET: $S3_BUCKET
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  CONFIGURE_ENCRYPTION_KEY: $CONFIGURE_ENCRYPTION_KEY

# Screenshots pipeline - triggered by PR label "generate screenshots"
steps:
  #################
  # Build Screenshots App
  #################
  - label: ":hammer_and_wrench: Build Screenshots App"
    key: build-screenshots
    command: .buildkite/commands/build-screenshots.sh
    plugins: [$CI_TOOLKIT]
    if: build.pull_request.labels includes "generate screenshots"
    artifact_paths:
      - "fastlane/DerivedData/Build/Products/Debug-iphonesimulator/WooCommerce.app/**/*"
      - "fastlane/DerivedData/Build/Products/Debug-iphonesimulator/WooCommerceScreenshots-Runner.app/**/*"
      - "screenshot-artifacts.tar"
    notify:
      - github_commit_status:
          context: Build Screenshots App

  #################
  # Generate Screenshots (Matrix)
  #################
  - label: ":camera: Generate Screenshots ({{matrix.language}} - {{matrix.mode}})"
    command: .buildkite/commands/take-screenshots.sh
    depends_on: build-screenshots
    plugins: [$CI_TOOLKIT]
    if: build.pull_request.labels includes "generate screenshots"
    matrix:
      setup:
        language:
          - ar
          - de-DE
          - en-US
          - es-ES
          - fr-FR
          - he
          - id
          - it
          - ja
          - ko
          - nl-NL
          - pt-BR
          - ru
          - sv
          - tr
          - zh-Hans
          - zh-Hant
        mode:
          - dark
          - light
    env:
      SCREENSHOT_LANGUAGE: "{{matrix.language}}"
      SCREENSHOT_MODE: "{{matrix.mode}}"
    artifact_paths:
      - "fastlane/logs/**/*"
    notify:
      - github_commit_status:
          context: "Generate Screenshots ({{matrix.language}} - {{matrix.mode}})"

  #################
  # Process Screenshots
  #################
  - label: ":framed_picture: Process Screenshots"
    command: .buildkite/commands/process-screenshots.sh
    depends_on: 
      - step: ":camera: Generate Screenshots ({{matrix.language}} - {{matrix.mode}})"
        allow_failure: false
    plugins: [$CI_TOOLKIT]
    if: build.pull_request.labels includes "generate screenshots"
    artifact_paths:
      - "fastlane/screenshots/**/*"
      - "fastlane/promo_screenshots/**/*"
    notify:
      - github_commit_status:
          context: Process Screenshots