# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: mac

env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: ":rocket: Nightly Prototype Build"
    command: .buildkite/commands/prototype-build.sh
    plugins: [$CI_TOOLKIT]
