import Foundation
import Yosemite

final class CustomersListViewModel: ObservableObject {
    let customers = [
        WCAnalyticsCustomer(siteID: 1,
                            customerID: 1,
                            userID: 0,
                            name: "Ann Jones",
                            email: "ajones@example.com",
                            username: nil,
                            dateRegistered: nil,
                            dateLastActive: Date(),
                            ordersCount: 0,
                            totalSpend: 0,
                            averageOrderValue: 0,
                            country: "",
                            region: "",
                            city: "",
                            postcode: ""),
        WCAnalyticsCustomer(siteID: 1,
                            customerID: 2,
                            userID: 2,
                            name: "John Smith",
                            email: "jsmith@example.com",
                            username: "jsmith",
                            dateRegistered: nil,
                            dateLastActive: Date(),
                            ordersCount: 0,
                            totalSpend: 0,
                            averageOrderValue: 0,
                            country: "",
                            region: "",
                            city: "",
                            postcode: ""),
        WCAnalyticsCustomer(siteID: 1,
                            customerID: 3,
                            userID: 0,
                            name: nil,
                            email: nil,
                            username: nil,
                            dateRegistered: nil,
                            dateLastActive: Date(),
                            ordersCount: 0,
                            totalSpend: 0,
                            averageOrderValue: 0,
                            country: "",
                            region: "",
                            city: "",
                            postcode: "")
    ]
}
