# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

########################################
# App Metadata
########################################

# The Bundle Identifier in App Store Connect
app_identifier "com.automattic.woocommerce"


# This folder has to include one folder for each language
screenshots_path "./promo_screenshots/"

# Make sure to update these keys for a new version
app_version "3.3"

privacy_url({
  'default' => 'https://automattic.com/privacy/',
})

copyright('2020 WooCommerce')

skip_binary_upload true
overwrite_screenshots true
phased_release true
