default_platform(:ios)
fastlane_require 'dotenv'

USER_ENV_FILE_PATH = File.join(Dir.home, '.wcios-env.default')
PROJECT_ENV_FILE_PATH = File.expand_path(File.join(Dir.pwd, '../.configure-files/project.env'))

# Use this instead of getting values from ENV directly
# It will throw an error if the requested value is missing
def get_required_env(key)
  unless ENV.key?(key)
    UI.user_error!("Environment variable '#{key}' is not set. Have you setup #{USER_ENV_FILE_PATH} correctly?")
  end
  ENV[key]
end

before_all do
  # Check that the env files exist
  unless is_ci || File.file?(USER_ENV_FILE_PATH)
    UI.user_error!("~/.wcios-env.default not found: Please copy env/user.env-example to #{USER_ENV_FILE_PATH} and fill in the values")
  end
  unless File.file?(PROJECT_ENV_FILE_PATH)
    UI.user_error!("project.env not found: Make sure your configuration is up to date with `rake dependencies`")
  end

  # This allows code signing to work on CircleCI
  # It is skipped if this isn't running on CI
  # See https://circleci.com/docs/2.0/ios-codesigning/
  setup_circle_ci
end

platform :ios do
########################################################################
# Environment
########################################################################
Dotenv.load(USER_ENV_FILE_PATH)
Dotenv.load(PROJECT_ENV_FILE_PATH)
ENV[GHHELPER_REPO="woocommerce/woocommerce-iOS"]
ENV["PROJECT_NAME"]="WooCommerce"
ENV["PUBLIC_CONFIG_FILE"]="config/Version.Public.xcconfig"
ENV["DOWNLOAD_METADATA"]="fastlane/download_metadata.swift"
ENV["PROJECT_ROOT_FOLDER"]="./"
ENV["APP_STORE_STRINGS_FILE_NAME"]="AppStoreStrings.pot"

########################################################################
# Release Lanes
########################################################################
  #####################################################################################
  # code_freeze
  # -----------------------------------------------------------------------------------
  # This lane executes the steps planned on code freeze
  # -----------------------------------------------------------------------------------
  # Usage:
  # bundle exec fastlane code_freeze [skip_confirm:<skip confirm>]
  #
  # Example:
  # bundle exec fastlane code_freeze
  # bundle exec fastlane code_freeze skip_confirm:true
  #####################################################################################
  desc "Creates a new release branch from the current develop"
  lane :code_freeze do | options |
    old_version = ios_codefreeze_prechecks(options)
    
    ios_bump_version_release()
    new_version = ios_get_app_version()
    ios_update_release_notes(new_version: new_version)
    setbranchprotection(repository:GHHELPER_REPO, branch: "release/#{new_version}")
    setfrozentag(repository:GHHELPER_REPO, milestone: new_version)

    ios_localize_project()
    ios_tag_build()
    get_prs_list(repository:GHHELPER_REPO, start_tag:"#{old_version}", report_path:"#{File.expand_path('~')}/wcios_prs_list_#{old_version}_#{new_version}.txt")
  end

  #####################################################################################
  # update_appstore_strings
  # -----------------------------------------------------------------------------------
  # This lane updates the AppStoreStrings.pot files with the latest content from
  # the release_notes.txt file and the other text sources
  # -----------------------------------------------------------------------------------
  # Usage:
  # bundle exec fastlane update_appstore_strings version:<release note version>
  #
  # Example:
  # bundle exec fastlane update_appstore_strings version:1.1
  #####################################################################################
  desc "Updates the AppStoreStrings.pot file with the latest data"
  lane :update_appstore_strings do | options |
    prj_folder = Pathname.new(File.join(Dir.pwd, "..")).expand_path.to_s
    source_metadata_folder = File.join(prj_folder, "fastlane/appstoreres/metadata/source")

    files = {
      whats_new: File.join(prj_folder,  "/WooCommerce/Resources/release_notes.txt"),
      app_store_subtitle: File.join(source_metadata_folder, "subtitle.txt"),
      app_store_desc: File.join(source_metadata_folder, "description.txt"),
      app_store_keywords: File.join(source_metadata_folder, "keywords.txt"),
      "app_store_promo_text" => File.join(source_metadata_folder, "app_store_promo_text.txt"),
      "app_store_screenshot-1" => File.join(source_metadata_folder, "promo_screenshot_1.txt"),
      "app_store_screenshot-1_b" => File.join(source_metadata_folder, "promo_screenshot_1_b.txt"),
      "app_store_screenshot-2" => File.join(source_metadata_folder, "promo_screenshot_2.txt"),
      "app_store_screenshot-3" => File.join(source_metadata_folder, "promo_screenshot_3.txt"),
      "app_store_screenshot-4" => File.join(source_metadata_folder, "promo_screenshot_4.txt"),
      "app_store_screenshot-5" => File.join(source_metadata_folder, "promo_screenshot_5.txt"),
      "app_store_screenshot-6" => File.join(source_metadata_folder, "promo_screenshot_6.txt"),
      "app_store_screenshot-7" => File.join(source_metadata_folder, "promo_screenshot_7.txt"),
      "app_store_screenshot-8" => File.join(source_metadata_folder, "promo_screenshot_8.txt")
    }

    ios_update_metadata_source(po_file_path: prj_folder + "/WooCommerce/Resources/AppStoreStrings.pot", 
      source_files: files, 
      release_version: options[:version])
  end

  #####################################################################################
  # new_beta_release
  # -----------------------------------------------------------------------------------
  # This lane updates the release branch for a new beta release. It will update the
  # current release branch by default. If you want to update a different branch
  # (i.e. hotfix branch) pass the related version with the 'base_version' param
  # (example: base_version:10.6.1 will work on the 10.6.1 branch)
  # -----------------------------------------------------------------------------------
  # Usage:
  # bundle exec fastlane new_beta_release [skip_confirm:<skip confirm>] [base_version:<version>]
  #
  # Example:
  # bundle exec fastlane new_beta_release
  # bundle exec fastlane new_beta_release skip_confirm:true
  # bundle exec fastlane new_beta_release base_version:10.6.1
  #####################################################################################
  desc "Updates a release branch for a new beta release"
  lane :new_beta_release do | options |
    ios_betabuild_prechecks(options)
    ios_bump_version_beta()
    ios_tag_build()
  end

  #####################################################################################
  # new_hotfix_release
  # -----------------------------------------------------------------------------------
  # This lane updates the release branch for a new hotix release. 
  # -----------------------------------------------------------------------------------
  # Usage:
  # bundle exec fastlane new_hotfix_release [skip_confirm:<skip confirm>] [version:<version>]
  #
  # Example:
  # bundle exec fastlane new_hotfix_release version:10.6.1
  # bundle exec fastlane new_hotfix_release skip_confirm:true version:10.6.1
  #####################################################################################
  desc "Creates a new hotfix branch from the given tag"
  lane :new_hotfix_release do | options |
    prev_ver = ios_hotfix_prechecks(options)
    ios_bump_version_hotfix(previous_version: prev_ver, version: options[:version])
    ios_tag_build()
  end

  #####################################################################################
  # finalize_release
  # -----------------------------------------------------------------------------------
  # This lane finalize a release: updates store metadata, pushes the final tag and  
  # cleans all the temp ones
  # -----------------------------------------------------------------------------------
  # Usage:
  # bundle exec fastlane finalize_release [skip_confirm:<skip confirm>] [version:<version>] 
  #
  # Example:
  # bundle exec fastlane finalize_release 
  # bundle exec fastlane finalize_release skip_confirm:true 
  #####################################################################################
  desc "Removes all the temp tags and puts the final one"
  lane :finalize_release do | options |
    ios_finalize_prechecks(options)
    ios_update_metadata(options) unless ios_current_branch_is_hotfix
    ios_bump_version_beta() unless ios_current_branch_is_hotfix
    ios_final_tag(options)
  end

  #####################################################################################
  # build_and_upload_release
  # -----------------------------------------------------------------------------------
  # This lane builds the app and upload it for distribution 
  # -----------------------------------------------------------------------------------
  # Usage:
  # bundle exec fastlane build_and_upload_release [skip_confirm:<skip confirm>]
  #
  # Example:
  # bundle exec fastlane build_and_upload_release 
  # bundle exec fastlane build_and_upload_release skip_confirm:true 
  #####################################################################################
  desc "Builds and updates for distribution"
  lane :build_and_upload_release do | options |
    ios_build_prechecks(skip_confirm: options[:skip_confirm], 
      internal: false,
      external: true)
    ios_build_preflight()
    build_and_upload_itc(skip_prechecks: true, skip_confirm: options[:skip_confirm])
  end

  #####################################################################################
  # build_and_upload_itc
  # -----------------------------------------------------------------------------------
  # This lane builds the app and upload it for external distribution  
  # -----------------------------------------------------------------------------------
  # Usage:
  # bundle exec fastlane build_and_upload_itc [skip_confirm:<skip confirm>]
  #
  # Example:
  # bundle exec fastlane build_and_upload_itc 
  # bundle exec fastlane build_and_upload_itc skip_confirm:true 
  #####################################################################################
  desc "Builds and updates for distribution"
  lane :build_and_upload_itc do | options |
    ios_build_prechecks(skip_confirm: options[:skip_confirm], external: true) unless (options[:skip_prechecks])
    ios_build_preflight() unless (options[:skip_prechecks])

    appstore_code_signing

    gym(scheme: "WooCommerce", workspace: "./WooCommerce.xcworkspace",
      clean: true, export_team_id: get_required_env("EXT_EXPORT_TEAM_ID"), 
      export_options: {
        method: "app-store"
      }
    )
    
    testflight(skip_waiting_for_build_processing: true)
    sh("cd .. && rm WooCommerce.ipa")

    sentry_upload_dsym(
      auth_token: get_required_env("SENTRY_AUTH_TOKEN"),
      org_slug: 'a8c',
      project_slug: 'woocommerce-ios',
      dsym_path: "./WooCommerce.app.dSYM.zip",
    )
    sh("cd .. && rm WooCommerce.app.dSYM.zip")
  end

  #####################################################################################
  # build_and_upload_installable_build
  # -----------------------------------------------------------------------------------
  # This lane builds the app and upload it for adhoc testing 
  # -----------------------------------------------------------------------------------
  # Usage:
  # bundle exec fastlane build_and_upload_installable_build [version_long:<version_long>]
  #
  # Example:
  # bundle exec fastlane build_and_upload_installable_build 
  # bundle exec fastlane build_and_upload_installable_build build_number:123 
  #####################################################################################
  desc "Builds and uploads an installable build"
  lane :build_and_upload_installable_build do | options |
    alpha_code_signing

    # Get the current build version, and update it if needed
    version_config_path = "../config/Version.Public.xcconfig"
    versions = Xcodeproj::Config.new(File.new(version_config_path)).to_hash
    build_number = versions["VERSION_LONG"]

    if options.key?(:build_number)
      build_number = options[:build_number]

      UI.message("Updating build version to #{build_number}")

      versions["VERSION_LONG"] = build_number
      new_config = Xcodeproj::Config.new(versions)
      new_config.save_as(Pathname.new(version_config_path))
    end

    gym(
      scheme: "WooCommerce Alpha",
      workspace: "WooCommerce.xcworkspace",
      export_method: "enterprise",
      clean: true,
      output_directory: "build",
      export_team_id: ENV["INT_EXPORT_TEAM_ID"],
      export_options: { method: "enterprise", iCloudContainerEnvironment: 'Production' })

    sh("mv ../build/WooCommerce.ipa \"../build/WooCommerce Alpha.ipa\"")
    
    # NOTE: "ipa" parameter is deprecated in appcenter_upload 1.6.0, but there's a bug in the action that
    # makes the default gym output override the "file" parameter. 
    appcenter_upload(
      api_token: get_required_env("APPCENTER_API_TOKEN"),
      owner_name: "automattic",
      owner_type: "organization", 
      app_name: "WooCommerce-Installable-Builds",
      ipa: "build/WooCommerce Alpha.ipa",
      destinations: "All-users-of-WooCommerce-Installable-Builds",
      notify_testers: false 
    )


    download_url = Actions.lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]
    UI.message("Successfully built and uploaded installable build here: #{download_url}")
    install_url = "https://install.appcenter.ms/orgs/automattic/apps/WooCommerce-Installable-Builds"

    # Create a comment.json file so that Peril to comment with the build details, if this is running on CI
    comment_body = "You can test the changes on this Pull Request by downloading it from AppCenter [here](#{install_url}) with build number: #{build_number}. IPA is available [here](#{download_url}). If you need access to this, you can ask a maintainer to add you."
    File.write("comment.json", { body: comment_body }.to_json)
  end

  ########################################################################
  # Screenshot Lanes
  ########################################################################  
  desc "Take Screenshots"
  lane :screenshots do | options |

    languages = get_required_env("MAGNIFICENT_16").split() + ["en"]

    if options[:languages] != nil
      languages = languages & options[:languages].split(",")
    end

    snapshot(
      clean: true,
      devices: [
        'iPhone 8',
      ],
      languages: languages,
      scheme: "WooCommerceScreenshots",
      output_directory: "./fastlane/screenshots",
      clear_previous_screenshots: true,
      erase_simulator: false,
      localize_simulator: true,
      concurrent_simulators: true,
    )

  end

  desc "Download App Store Translations"
  lane :download_app_store_translations do | options |

    files = {

      # Metadata fields
      "app_store_desc"            => {desc: "description.txt"},
      "app_store_keywords"        => {desc: "keywords.txt"},
      "app_store_subtitle"        => {desc: "subtitle.txt"},
      "app_store_promo_text"      => {desc: "promotional_text.txt"},
      "whats_new"                 => {desc: "whats_new.txt"},

      # Screenshots
      "app_store_screenshot-1"    => {desc: "app_store_screenshot_1.txt"},
      "app_store_screenshot-1_b"  => {desc: "app_store_screenshot_1b.txt"},
      "app_store_screenshot-2"    => {desc: "app_store_screenshot_2.txt"},
      "app_store_screenshot-3"    => {desc: "app_store_screenshot_3.txt"},
      "app_store_screenshot-4"    => {desc: "app_store_screenshot_4.txt"},
      "app_store_screenshot-5"    => {desc: "app_store_screenshot_5.txt"},
      "app_store_screenshot-6"    => {desc: "app_store_screenshot_6.txt"},
      "app_store_screenshot-7"    => {desc: "app_store_screenshot_7.txt"},
      "app_store_screenshot-8"    => {desc: "app_store_screenshot_8.txt"},
    }

    metadata_locales = get_required_env("MAGNIFICENT_16").split().map { |locale| locale.downcase }

    gp_downloadmetadata(project_url: "https://translate.wordpress.com/projects/woocommerce%2Fwoocommerce-ios%2Frelease-notes/", 
      target_files: files,
      locales: metadata_locales,
      source_locale: "en-US",
      download_path: "./fastlane/metadata"
    )

    # Create the marketing and privacy URL files
    metadata_locales.each { |locale|
      marketing_path = Dir.pwd + "/metadata/#{locale}/marketing_url.txt"
      write_file(marketing_path, 'https://woocommerce.com/mobile/')
      
      privacy_path = Dir.pwd + "/metadata/#{locale}/privacy_url.txt"
      write_file(privacy_path, "https://automattic.com/privacy/")

      support_path = Dir.pwd + "/metadata/#{locale}/support_url.txt"
      write_file(support_path, "https://docs.woocommerce.com/")
    }
  end

  desc "Upload App Store Data"
  lane :upload_app_store_data do | options |
    
    deliver(
      app_identifier: 'com.automattic.woocommerce',
      copyright: '2019 WooCommerce',
      skip_binary_upload: true,
      team_id: '299112',
      skip_screenshots: true,
      ignore_language_directory_validation: true
    )
  end

  desc "Create Promo Screenshots"
  lane :create_promo_screenshots do | options |

    if !Fastlane::Helper::GitHelper.has_git_lfs then
      UI.user_error!("LFS not enabled – unable to generate promo screenshots. Run `git lfs install && git lfs fetch && git lfs pull` to fix this.")
    end

    # Create a copy of the files to work with – this ensures that if we're doing multiple
     # screenshot generation tasks close together, we can keep reusing the same source files
     original_screenshot_directory = File.join(Dir.pwd, "screenshots")
     metadata_directory = File.join(Dir.pwd, "metadata")
     output_directory = File.join(Dir.pwd, "/promo_screenshots")

     # Run screenshots generator tool 
     promo_screenshots(
       orig_folder: original_screenshot_directory,
       metadata_folder: metadata_directory,
       output_folder: output_directory,
       force: options[:force],
     )
  end

  ########################################################################
  # Fastlane match code signing
  ########################################################################
  private_lane :alpha_code_signing do |options|
    match(
      type: "enterprise",
      team_id: get_required_env("INT_EXPORT_TEAM_ID"),
      readonly: options[:readonly] || is_ci,
      app_identifier: ["com.automattic.alpha.woocommerce"])
  end

  private_lane :appstore_code_signing do |options|
    match(
      type: "appstore",
      team_id: get_required_env("EXT_EXPORT_TEAM_ID"),
      readonly: options[:readonly] || is_ci,
      app_identifier: ["com.automattic.woocommerce"])
  end

  ########################################################################
  # Helper Lanes
  ########################################################################  
  desc "Get a list of pull request from `start_tag` to the current state"
  lane :get_pullrequests_list do | options |
    get_prs_list(repository:GHHELPER_REPO, start_tag:"#{options[:start_tag]}", report_path:"#{File.expand_path('~')}/wcios_prs_list.txt")
  end

  desc "Run release preflight checks"
  lane :release_preflight do | options |
      configure_validate()
  end

  def write_file(path, contents)
    begin
      FileUtils.rm_f(path)
      file = File.new(path, "w")
      file.write(contents) 
    rescue IOError => e
      UI.crash(e)
    ensure
      file.close unless file.nil?
    end
  end
end
