default_platform(:ios)
fastlane_require 'dotenv'

platform :ios do
########################################################################
# Environment
########################################################################
Dotenv.load('~/.wcios-env.default')
ENV[GHHELPER_REPO="woocommerce/woocommerce-iOS"]

########################################################################
# Helper Lanes
########################################################################  
desc "Get a list of pull request from `start_tag` to the current state"
lane :get_pullrequests_list do | options |
  get_prs_list(repository:GHHELPER_REPO, start_tag:"#{options[:start_tag]}", report_path:"#{File.expand_path('~')}/wcios_prs_list.txt")
end

desc "Run release preflight checks"
lane :release_preflight do | options |
    configure_validate()
end

end
