steps:
  - label: "Complete Code Freeze"
    plugins:
      - automattic/a8c-ci-toolkit#3.0.1
    env:
      # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
      IMAGE_ID: xcode-15.4
    command: |
      .buildkite/commands/configure-environment.sh

      echo '--- :git: Checkout Release Branch'
      .buildkite/commands/checkout-release-branch.sh

      echo '--- :closed_lock_with_key: Access Secrets'
      bundle exec fastlane run configure_apply

      echo '--- :snowflake: Complete Code Freeze'
      bundle exec fastlane complete_code_freeze skip_confirm:true
    retry:
      manual:
        allowed: false
