steps:
  - label: "Finalize Hotfix Release"
    plugins:
      - automattic/a8c-ci-toolkit#3.0.1
    env:
      # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
      IMAGE_ID: xcode-15.2-v2
    command: |
      .buildkite/commands/configure-environment.sh

      echo '--- :git: Checkout Release Branch'
      .buildkite/commands/checkout-release-branch.sh

      echo '--- :closed_lock_with_key: Access Secrets'
      bundle exec fastlane run configure_apply

      echo '--- :fire: Finalize Hotfix Release'
      bundle exec fastlane finalize_hotfix_release skip_confirm:true
