steps:
  - label: "Finalize Release"
    agents:
      queue: mac
    plugins:
      - automattic/a8c-ci-toolkit#3.0.1
      - automattic/git-s3-cache#1.1.4:
        bucket: "a8c-repo-mirrors"
        # This is not necessarily the actual name of the repo or the GitHub organization
        # it belongs to. It is the key used in the bucket, which is set based on
        # the Buildkite pipeline slug
        repo: "automattic/woocommerce-ios/"
    env:
      # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
      IMAGE_ID: xcode-14.3.1
    command: |
      .buildkite/commands/configure-environment.sh

      bundle exec fastlane finalize_release skip_confirm:true
