import UIKit
import Gridicons


// MARK: - OrderNoteTableViewCell
//
class OrderNoteTableViewCell: UITableViewCell {

    /// Top Left Icon
    ///
    @IBOutlet private var iconButton: UIButton!

    /// Top Right Label
    ///
    @IBOutlet private var statusLabel: UILabel!

    /// Bottom Text View
    ///
    @IBOutlet private var noteTextView: UITextView!


    // MARK: - View Lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()

        configureBackground()
        configureStatusLabel()
        configureNoteTextView()
        configureIconButton()
    }

    /// Indicates if the note is visible to the Customer (or it's set to private!)
    ///
    var isCustomerNote: Bool = false {
        didSet {
            noteTypeWasUpdated()
        }
    }

    /// Indicates if the note was generated by the system
    ///
    var isSystemAuthor: Bool = false {
        didSet {
            noteTypeWasUpdated()
        }
    }

    var author: String? {
        didSet {
            noteTypeWasUpdated()
        }
    }

    var dateCreated: String? {
        didSet {
            noteTypeWasUpdated()
        }
    }

    /// Note's Payload
    ///
    var contents: String? {
        get {
            return noteTextView.text
        }
        set {
            noteTextView.text = newValue
        }
    }

    override func updateConfiguration(using state: UICellConfigurationState) {
        super.updateConfiguration(using: state)
        updateDefaultBackgroundConfiguration(using: state)
    }
}


// MARK: - Private Methods
//
private extension OrderNoteTableViewCell {

    /// Updates the Status Label + Icon's Color
    ///
    func noteTypeWasUpdated() {
        let theAuthor = author ?? ""
        let dateOfCreation = dateCreated ?? ""
        if isCustomerNote {
            iconButton.backgroundColor = .primary
            let template =
                NSLocalizedString("%1$@ - %2$@ (To Customer)",
                                  comment: "This text appears as a label in the order details screen to identify order notes that are visible to the customer. It displays in the format of timestamp - author name (To Customer) to help merchants distinguish customer-facing notes from private or system notes.")
            statusLabel.text = String.localizedStringWithFormat(template, dateOfCreation, theAuthor)
        } else if isSystemAuthor {
            iconButton.backgroundColor = .listSmallIcon
            let template =
                NSLocalizedString("%1$@ - %2$@ (System)",
                                  comment: "This text appears as a label for order notes in the order details screen, specifically identifying system-generated status messages. The format displays the timestamp and author followed by \"(System)\" to indicate the note was automatically created by the system rather than manually added.")
            statusLabel.text = String.localizedStringWithFormat(template, dateOfCreation, theAuthor)
        } else {
            iconButton.backgroundColor = .textSubtle
            let template =
                NSLocalizedString("%1$@ - %2$@ (Private)",
                                  comment: "This text appears as a status label in order note cells within the order details screen, indicating that the note is private and not visible to customers. It displays in the format 'time - author (Private)' to help merchants distinguish between different types of order notes.")
            statusLabel.text = String.localizedStringWithFormat(template, dateOfCreation, theAuthor)
        }
    }

    func configureBackground() {
        configureDefaultBackgroundConfiguration()
    }

    /// Setup: Status Label
    ///
    func configureStatusLabel() {
        statusLabel.applyBodyStyle()
        statusLabel.textColor = .textSubtle
    }

    /// Setup: Note Content Text View
    ///
    func configureNoteTextView() {
        noteTextView.font = .body
        noteTextView.textColor = .text
        noteTextView.backgroundColor = .listForeground(modal: false)
        noteTextView.adjustsFontForContentSizeCategory = true

        // Remove padding from inside text view
        noteTextView.contentInset = .zero
        noteTextView.textContainerInset = .zero
        noteTextView.textContainer.lineFragmentPadding = .zero
    }

    /// Setup: Icon Button
    ///
    func configureIconButton() {
        iconButton.setImage(.asideImage, for: .normal)
        iconButton.layer.cornerRadius = iconButton.frame.width / 2
        iconButton.tintColor = .neutral(.shade0)
    }
}
